spring:
  application:
    name: catalogo-svc
  datasource:
    url: jdbc:postgresql://localhost:5433/catalogo_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate # Dejamos que Flyway maneje el esquema
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true # Crea la tabla de metadatos de Flyway si no existe

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html
